variables:
  azureContainerRegistry: istahiacr.azurecr.io
  azureSubscriptionEndpoint: /subscriptions/3f1d8a91-940f-4c9d-b8d7-b146893bbd27/resourceGroups/istahiContainersBootcamp/providers/Microsoft.Web/sites/istahi-multicontainer
steps:
- task: DockerCompose@0
  displayName: Container registry login
  inputs:
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
- task: DockerCompose@0
  displayName: Build services
  inputs:
    action: Build services
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: docker-compose.yml
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
    additionalImageTags: $(Build.BuildId)